//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOI.SISAC.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VOI.SISAC.Business.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation process is executing..
        /// </summary>
        internal static string CalculationProcessOnExecution {
            get {
                return ResourceManager.GetString("CalculationProcessOnExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate primary key..
        /// </summary>
        internal static string DuplicatePrimaryKey {
            get {
                return ResourceManager.GetString("DuplicatePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate value..
        /// </summary>
        internal static string DuplicateValue {
            get {
                return ResourceManager.GetString("DuplicateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete record..
        /// </summary>
        internal static string FailedDeleteRecord {
            get {
                return ResourceManager.GetString("FailedDeleteRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find record..
        /// </summary>
        internal static string FailedFindRecord {
            get {
                return ResourceManager.GetString("FailedFindRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to insert record..
        /// </summary>
        internal static string FailedInsertRecord {
            get {
                return ResourceManager.GetString("FailedInsertRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve records from database. .
        /// </summary>
        internal static string FailedRetrievedRecords {
            get {
                return ResourceManager.GetString("FailedRetrievedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update record..
        /// </summary>
        internal static string FailedUpdateRecord {
            get {
                return ResourceManager.GetString("FailedUpdateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See inner exception..
        /// </summary>
        internal static string SeeInnerException {
            get {
                return ResourceManager.GetString("SeeInnerException", resourceCulture);
            }
        }
    }
}
