//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOI.SISAC.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VOI.SISAC.Web.Resources.LogMessages", typeof(LogMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN DELETE TRANSACTION IN {0} FROM {1}.
        /// </summary>
        internal static string BeginDelete {
            get {
                return ResourceManager.GetString("BeginDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN INSERT TRANSACTION IN {0} FROM {1}.
        /// </summary>
        internal static string BeginInsert {
            get {
                return ResourceManager.GetString("BeginInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN UPDATE TRANSACTION IN {0} FROM {1}.
        /// </summary>
        internal static string BeginUpdate {
            get {
                return ResourceManager.GetString("BeginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMIT TRANSACTION.
        /// </summary>
        internal static string CommitTransaction {
            get {
                return ResourceManager.GetString("CommitTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR WHEN TRYING TO CREATE THE FILE IN {0} FROM {1}.
        /// </summary>
        internal static string CreationFileError {
            get {
                return ResourceManager.GetString("CreationFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER IN {0} FROM {1}.
        /// </summary>
        internal static string EnterIn {
            get {
                return ResourceManager.GetString("EnterIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR IN AUTHENTICATION PROCESS.
        /// </summary>
        internal static string ErrorAuthenticate {
            get {
                return ResourceManager.GetString("ErrorAuthenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR CREATING {0} FROM {1}.
        /// </summary>
        internal static string ErrorCreate {
            get {
                return ResourceManager.GetString("ErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR DELETING {0} FROM {1}.
        /// </summary>
        internal static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR IN INACTIVATE SERVICE CONTRACT FROM {0}.
        /// </summary>
        internal static string ErrorInactiveContractService {
            get {
                return ResourceManager.GetString("ErrorInactiveContractService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR NULL REFERENCE {0}.
        /// </summary>
        internal static string ErrorNullObject {
            get {
                return ResourceManager.GetString("ErrorNullObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR TRYING PARSE TO DATETIME IN {0} FROM {1}.
        /// </summary>
        internal static string ErrorParsingDate {
            get {
                return ResourceManager.GetString("ErrorParsingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the File..
        /// </summary>
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR RETRIEVING {0} FROM {1}.
        /// </summary>
        internal static string ErrorRetrieveInfo {
            get {
                return ResourceManager.GetString("ErrorRetrieveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR UPDATING {0} FROM {1}.
        /// </summary>
        internal static string ErrorUpdate {
            get {
                return ResourceManager.GetString("ErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEGIN SELECT {0} FROM {1}.
        /// </summary>
        internal static string FindRecord {
            get {
                return ResourceManager.GetString("FindRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FROM {0}/{1}, ON PC {2}..
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
